name: strongweak
version: 0.4.1
synopsis: Convert between strong and weak representations of types
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Data
tested-with: GHC ==9.2.2
license: MIT
license-file: LICENSE

github: raehik/strongweak
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

# `pkg ^>= x.y.z` means `pkg >= x.y.z && < x.(y+1)
dependencies:
- base >= 4.14 && < 5
- either ^>= 5.0.1.1
- prettyprinter ^>= 1.7.1
- refined >= 0.7 && < 0.9
- vector-sized ^>= 1.5.0
- vector >= 0.12.3.1 && < 0.14
- text # TODO

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    build-tools:
    - hspec-discover >= 2.7 && < 2.10
    dependencies:
    - strongweak
    - hspec >= 2.7 && < 2.11
    - QuickCheck ^>= 2.14.2
    - quickcheck-instances ^>= 0.3.26
    - generic-random ^>= 1.5.0.1
